spring:
    profiles:
        active: local
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:ff2011
        username: local
        password: local
        driver-class-name: oracle.jdbc.OracleDriver
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML

jpa:
    hibernate:
        ddl-auto: none
        sql: debug
    properties:
        hibernate:
            show_sql: true
            format_sql: true
            use_sql_comments: true

logging.level:
#  org.hibernate.SQL: debug
    org.hibernate.type: trace




